#淘汰策略
replacement: 
#最大内存空间
  max-bytes: 1000000
#使用的淘汰策略
  policy: LFU

#默认虚拟节点个数
defaultReplicas: 50

#服务配置
peer:
  #IP地址
  address: 127.0.0.1
  #端口
  port: 8086

slave:
  #IP地址
  address: 127.0.0.1
  #端口
  port: 8080

save:
  seconds: 5
  modify: 1